### ISSUE TITLE
reloading bundle exec ruby app.rb

### ISSUE THREAD

**Issue by ghost** [ga-dc/wdinstagram#4]
Why do we have to reload this every time we change our controllers and views? We don't have to do that if we change our css.

**Comment by mattscilipoti** [comment]
It should be doing that.  I checked here http://www.sinatrarb.com/contrib/reloader.html. We have seen that it doesn't work... sometimes, and that is difficult when you don't know what to trust.

My hypothesis was that the newly added `require 'bundler/setup'` was causing an issue with the reloading, but our experimentation proved otherwise.  Unfortunately, it just worked for us.  This will be better in Rails.  It is more robust and has clearer expectations.
